name: story_space
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  http: ^1.2.2
  fpdart: ^1.1.0
  shared_preferences: ^2.2.3
  path: ^1.9.0
  image: ^3.2.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  email_validator: ^3.0.0
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  infinite_scroll_pagination: ^4.0.0
  google_maps_flutter: ^2.2.8
  geocoding: ^3.0.0
  location: ^6.0.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  freezed: ^2.5.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/svg/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
